services:
  grafana:
    image: grafana/grafana:10.4.15
    container_name: grafana
    user: "0:0"
    environment:
      GF_AUTH_ALLOWED_ORGANIZATIONS: h2-asset
      GF_AUTH_GITHUB_CLIENT_ID: ${GRAFANA_AUTH_GITHUB_CLIENT_ID}
      GF_AUTH_GITHUB_CLIENT_SECRET: ${GRAFANA_AUTH_GITHUB_CLIENT_SECRET}
      GF_AUTH_GITHUB_ENABLED: true
      GF_AUTH_GITHUB_SKIP_ORG_ROLE_SYNC: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/1-global-db-overview.json
      GF_INSTALL_PLUGINS: marcusolsson-treemap-panel
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_SECURITY_ADMIN_USER: admin
      GF_SERVER_ROOT_URL: ${GRAFANA_SERVER_ROOT_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - "../grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/pgwatch_dashboards.yml"
      - "../grafana/postgres_datasource.yml:/etc/grafana/provisioning/datasources/postgres_datasource.yml"
      - "../grafana/postgres/v10:/var/lib/grafana/dashboards"
    depends_on:
      postgres:
        condition: service_healthy